# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from multi_pub_package/stateMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class stateMsg(genpy.Message):
  _md5sum = "cf8f7c0f25f41a1e73275e44245843a9"
  _type = "multi_pub_package/stateMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 sN1
float64 x1
float64 y1
float64 yaw1
float64 sN2
float64 x2
float64 y2
float64 yaw2
"""
  __slots__ = ['sN1','x1','y1','yaw1','sN2','x2','y2','yaw2']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sN1,x1,y1,yaw1,sN2,x2,y2,yaw2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(stateMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sN1 is None:
        self.sN1 = 0.
      if self.x1 is None:
        self.x1 = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.yaw1 is None:
        self.yaw1 = 0.
      if self.sN2 is None:
        self.sN2 = 0.
      if self.x2 is None:
        self.x2 = 0.
      if self.y2 is None:
        self.y2 = 0.
      if self.yaw2 is None:
        self.yaw2 = 0.
    else:
      self.sN1 = 0.
      self.x1 = 0.
      self.y1 = 0.
      self.yaw1 = 0.
      self.sN2 = 0.
      self.x2 = 0.
      self.y2 = 0.
      self.yaw2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.sN1, _x.x1, _x.y1, _x.yaw1, _x.sN2, _x.x2, _x.y2, _x.yaw2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.sN1, _x.x1, _x.y1, _x.yaw1, _x.sN2, _x.x2, _x.y2, _x.yaw2,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d().pack(_x.sN1, _x.x1, _x.y1, _x.yaw1, _x.sN2, _x.x2, _x.y2, _x.yaw2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.sN1, _x.x1, _x.y1, _x.yaw1, _x.sN2, _x.x2, _x.y2, _x.yaw2,) = _get_struct_8d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
